---
title: "FIN450 Final Assignment"
output: html_document
date: "2023-11-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(tidyverse)
library(RSelenium)
library(netstat)
library(jsonlite)
library(robotstxt)
library(rvest)
library(openxlsx)

```

```{r remDr Start}
# Start the server
rs_driver_object <- rsDriver(browser = "firefox",
                             chromever = NULL,
                             verbose = FALSE
                             )

# Create a Client object
remDr <- rs_driver_object$client
```

```{r scraping new release}
library(rvest)
library(stringr)
library(dplyr)
library(tidyr)

# Replace 'your_url_here' with the actual URL of the webpage
url <- "https://www.imdb.com/calendar/?ref_=rlm&region=US&type=MOVIE"

# Read the HTML content of the webpage
webpage <- read_html(url)

# Use the identified CSS selector for the movie elements
movie_elements <- html_nodes(webpage, '.ipc-metadata-list-summary-item')

# Initialize an empty list to store data for each movie
movies_data <- list()

# Loop through each movie element
for (i in seq_along(movie_elements)) {
  # Extract title
  title <- html_text(html_node(movie_elements[[i]], '.ipc-metadata-list-summary-item__t'))

  # Extract year (assuming it's within the title link)
  year <- gsub("[^0-9]", "", str_match(title, "\\((\\d{4})\\)")[, 2])

  # Extract genres
  genres <- html_text(html_nodes(movie_elements[[i]], '.ipc-inline-list--show-dividers.ipc-metadata-list-summary-item__tl .ipc-inline-list__item'))

  # Extract stars
  stars <- html_text(html_nodes(movie_elements[[i]], '.ipc-inline-list--show-dividers.ipc-metadata-list-summary-item__stl .ipc-inline-list__item'))

  # Store the data for the current movie in a list
  movie_data <- list(title = title, year = year, genres = paste(genres, collapse = ", "), stars = paste(stars, collapse = ", "))

  # Append the list to the movies_data list
  movies_data <- append(movies_data, list(movie_data))
}

# Convert the list of lists into a data frame
new_movies_df <- bind_rows(movies_data)

# Print the resulting data frame
print(new_movies_df)

```

```{r Revenue For the top movies_per_page movies of each year from 2024 - num_pages}

#Scrapes the revenue of each movie flipping through each year.
scrape_revenue_data <- function(num_pages) {
  all_data <- list()  # Initialize an empty list to store the collected data

  for (page in 1:(num_pages)) {
    # Click the year drop down
    drop_down <- remDr$findElement(using = 'css selector', '.mojo-refinement')$clickElement()
    remDr$findElement(using = 'css selector',  paste0('li.a-dropdown-item:nth-child(', page, ')'))$clickElement()
    
    # Pause
    Sys.sleep(1)
    
    # Read the HTML of the current page
    url <- as.character(remDr$getCurrentUrl())
    webpage <- read_html(url)
    
    # Extract the table data 
    table_data <- webpage %>% 
      html_nodes("#table table") %>% 
      html_table(fill = TRUE)
    
    # Add the "Year" column
    table_data <- lapply(table_data, function(df) { df$Year <- 2024 - page; return(df) })
    
    # Add the data to the overall list
    all_data <- c(all_data, list(table_data))
  }
  
  return(all_data)
}

```

```{r Extract Movie Specific Data}

#Scrapes the Movie specific data, returns a wide df of the movie's data
extract_movie_data <- function(webpage, title) {
  # Target the specific div that contains the table rows
  table_nodes <- webpage %>% 
    html_nodes(".mojo-summary-values .a-section.a-spacing-none")
  
  # Initialize empty lists to store headers and values
  headers <- c()
  values <- c()
  
  # Iterate through each table row
  for (node in table_nodes) {
    # Extract the header
    header <- node %>% html_node("span:nth-child(1)") %>% html_text()
    
    # Extract the value
    value_node <- node %>% html_node("span:nth-child(2)")
    value <- value_node %>% html_text(trim = TRUE)
    
    # Append the header and value to the lists
    headers <- c(headers, header)
    values <- c(values, value)
  }
  
  # Combine headers and values into a data frame
  table_data <- data.frame(Header = headers, Value = values)
  table_data$Title <- title
  movie_wide <- table_data %>% 
    tidyr::pivot_wider(names_from = Header, values_from = Value)
  
  # Collect crew table
  crew_table <- webpage %>% 
    html_nodes("#principalCrew") %>% 
    html_table(fill = TRUE)
 
  if (length(crew_table) == 0) {
    crew_df <- data.frame(Crew = character(), stringsAsFactors = FALSE)
  } else {
    # If cast_table is not empty, proceed with data processing
    crew_df <- crew_table[[1]] %>% 
    group_by(Role) %>% 
    summarize(NameCombined = paste(Filmmakers, collapse = ", ")) %>% 
    ungroup() %>% 
    pivot_wider(names_from = Role, 
                values_from = NameCombined)
  }
  
  # Collect Cast table
  cast_table <- webpage %>% 
    html_nodes("#principalCast") %>% 
    html_table(fill = TRUE)

  # Check if cast_table is not empty before proceeding
  if (length(cast_table) == 0) {
    cast_df <- data.frame(Cast = character(), stringsAsFactors = FALSE)
  } else {
    # If cast_table is not empty, proceed with data processing
    cast_df <- cast_table[[1]] %>% 
      as.data.frame() %>% 
      mutate(Cast = paste(Cast, collapse = ", ")) %>% 
      pull(Cast) %>% 
      unname() %>% 
      tibble(Cast = .) %>% 
      dplyr::distinct(Cast)
  }
  
  if (!is.null(cast_df) && nrow(cast_df) > 0) {
    df_wide <- cbind(movie_wide, cast_df, crew_df)
  } else {
    df_wide <- cbind(movie_wide, crew_df)
  }

  
  return(df_wide)
}

```

```{r Flip through Movies within each Year and Aggregate}

# Flips through each Movie within each Year and aggregates the specific year's movie data
scrape_movie_data <- function(movie_titles) {
  movie_df <- tibble()
  for (title in movie_titles) {
    # Find and click the link for the current movie title
    address <- as.character(remDr$getCurrentUrl())
    movie_link <- remDr$findElement(using = 'link text', title)$clickElement()
    
    
    print(title)
    remDr$findElement(using = 'link text', 'Title Summary')$clickElement()
    remDr$findElement(using = 'link text', 'Cast and Crew')$clickElement()
    
    url <- as.character(remDr$getCurrentUrl())
    webpage <- read_html(url)
    movie_data <- extract_movie_data(webpage, title)
    
    # Append the movie_data to the global movie_df
    movie_df <- bind_rows(movie_df, movie_data)
    
    remDr$navigate(address)
    
    # Pause
    Sys.sleep(1)
  }
  return(movie_df)
}

```

```{r Flip through Each year and Aggregate each year's movie data}

#Flips through each year and aggregates all year's data
scrape_and_aggregate_data <- function(num_pages, movies_per_page, movie_titles) {
  # Initialize an empty data frame to store aggregated movie data
  final_df <- tibble()
  
  for (page in 1:num_pages) {
    # Calculate the start and end indices for the current page
    start_index <- (page - 1) * movies_per_page + 1
    end_index <- page * movies_per_page
    
    # Extract movie titles for the current page
    current_page_titles <- movie_titles[start_index:end_index]
    
    # Scrape movie specific data
    movie_df <- scrape_movie_data(current_page_titles)
    final_df <- bind_rows(final_df, movie_df)
    
    # Click the year drop down
    drop_down <- remDr$findElement(using = 'css selector', '.mojo-refinement')$clickElement()
    remDr$findElement(using = 'css selector', paste0('li.a-dropdown-item:nth-child(', page + 1, ')'))$clickElement()
    
    # Pause
    Sys.sleep(1)
  }
  
  return(final_df)
}
```

```{r MAIN}
website <- 'https://www.boxofficemojo.com/'
remDr$open()
remDr$navigate(website)
alltime <- remDr$findElement(using = 'link text', 'Worldwide')$clickElement()

#RUN EVERYTHING UNDER HERE TO TEST 

#CHANGE AS NEEDED
num_pages <- 25 
movies_per_page <- 75

# Collect Revenue data
result_data <- scrape_revenue_data(num_pages)
rev_df <- bind_rows(result_data)
rev_df$`Release Group` <- gsub("\\s{2,}(Re-release)", " \\1", rev_df$`Release Group`)
rev_df <- rev_df %>% 
  dplyr::filter(Rank <= movies_per_page)

rev_df

movie_titles <- rev_df$`Release Group`

# Return to first page
drop_down <- remDr$findElement(using = 'css selector', '.mojo-refinement')$clickElement()
remDr$findElement(using = 'css selector',  paste0('li.a-dropdown-item:nth-child(1)'))$clickElement()


movie_df <- scrape_and_aggregate_data(num_pages, movies_per_page, movie_titles)

# Aggregate movie_df and rev_df 
combined_df <- cbind(rev_df, movie_df)

combined_df

# Change File Location to save data
write.xlsx(combined_df, 'C:/Users/jamie/OneDrive/School/FALL 2023/FIN 450/Final/FIN450-Final/scraped_data.xlsx', rowNames = FALSE)
```

```{r Data Wrangling and Parsing}

temp <- combined_df %>% 
  dplyr::select(-Title)

df <- temp[, -15] %>% 
  dplyr::rename(Title = `Release Group`,
                `% Domestic` = `%...5`,
                `% Foreign` = `%...7`,
                Distributor = `Domestic Distributor`) %>% 
  dplyr::mutate(Distributor = sub("See full company information$", "", Distributor),
                Worldwide = parse_number(gsub("[$,]", "", Worldwide)),
                Domestic = parse_number(gsub("[$,]", "", Domestic)),
                Foreign = parse_number(gsub("[$,]", "", Foreign)),
                `Domestic Opening` = parse_number(gsub("[$,]", "", `Domestic Opening`)),
                Budget = parse_number(gsub("[$,]", "", Budget)),
                `% Domestic` = as.numeric(parse_number(`% Domestic`)) / 100,
                `% Foreign` = as.numeric(parse_number(`% Foreign`)) / 100,
                `Earliest Release Date` = mdy(str_extract(`Earliest Release Date`, "[A-Za-z]+ [0-9]+, [0-9]+")),
                Hours = as.numeric(str_extract(`Running Time`, "\\d+(?= hr)")),
                Minutes = as.numeric(str_extract(`Running Time`, "\\d+(?= min)")),
                Hours = ifelse(is.na(Hours), 0, Hours),
                Minutes = ifelse(is.na(Minutes), 0, Minutes),
                `Run Time (Mins)` = Hours * 60 + Minutes,
                Genres = strsplit(Genres, "\r\n[[:space:]]*\\r\\n"),
                Genres = sapply(Genres, function(x) paste(trimws(x), collapse = ", "))) %>%
                select(-c(`Running Time`, Hours, Minutes))

df
```


